"""Notification endpoints — Sprint 5.7.

Two routes for managing per-device push registrations:

* ``POST /users/me/notification-tokens`` — upsert this device's FCM
  token. Called by the Flutter app on every cold start (FCM tokens
  rotate silently, so heartbeating is the right correctness model).
* ``DELETE /users/me/notification-tokens/{installation_id}`` —
  remove this device. Called on explicit sign-out.

A third route fires a scheduler tick — see the worker / cron section
of the project plan. Kept here so the same auth + tenant-scope
plumbing applies:

* ``POST /admin/notifications/run-scheduler`` — runs one scheduler
  tick across the caller's tenant. Tenant-admin only. Returns a
  summary so an operator can sanity-check what would fire.

Why ``/users/me`` and not ``/users/{id}``
-----------------------------------------
A device only ever knows the JWT-authenticated user — letting clients
pass an arbitrary user_id would invite a spoofing attack where one
student registers a token under another's account. Anchoring to the
caller's ``current_user.id`` removes the surface entirely.
"""

from __future__ import annotations

import logging

from fastapi import APIRouter, Depends, Response, status
from pydantic import BaseModel, Field

from app.core.auth import get_current_user, require_role
from app.models.notification import DevicePlatform
from app.models.user import User, UserRole
from app.services import notifications as notification_service
from app.workers import notification_scheduler as scheduler

logger = logging.getLogger(__name__)

users_router = APIRouter(prefix="/users/me", tags=["notifications"])
admin_router = APIRouter(prefix="/admin/notifications", tags=["notifications"])


# ── Wire types ─────────────────────────────────────────────────────────────


class NotificationTokenRegistration(BaseModel):
    """Request body for ``POST /users/me/notification-tokens``."""

    installation_id: str = Field(
        min_length=1,
        max_length=128,
        description=(
            "Stable per-install UUID generated by the Flutter app. "
            "Re-installs MUST mint a fresh value so the backend "
            "replaces the old row instead of stacking duplicates."
        ),
    )
    token: str = Field(
        min_length=1,
        max_length=4096,
        description="The current FCM token for this installation.",
    )
    platform: DevicePlatform


class NotificationTokenResponse(BaseModel):
    """Echoed registration confirming what the backend stored.

    The Flutter side uses ``last_seen_at`` to know whether its
    heartbeat refresh actually landed (some Flutter networks swallow
    success codes silently and a stale ``last_seen_at`` is the
    trigger to retry on next launch).
    """

    installation_id: str
    token: str
    platform: DevicePlatform
    registered_at: str
    last_seen_at: str


class SchedulerTickSummary(BaseModel):
    """Response body for the admin scheduler-tick endpoint."""

    study_reminders_sent: int
    streak_warnings_sent: int
    unanswered_reprompts_sent: int = 0
    students_evaluated: int
    failures: int


# ── Token endpoints ────────────────────────────────────────────────────────


@users_router.post(
    "/notification-tokens",
    response_model=NotificationTokenResponse,
    status_code=status.HTTP_201_CREATED,
)
async def register_notification_token(
    body: NotificationTokenRegistration,
    current_user: User = Depends(get_current_user),
) -> NotificationTokenResponse:
    """Upsert this device's push registration.

    Always returns 201 — the registration is upserted, so "already
    registered" isn't a separate response. ``last_seen_at`` always
    bumps to wall-clock now so heartbeats are observable.
    """
    token = await notification_service.register_token(
        tenant_id=current_user.tenant_id,
        user_id=current_user.id,
        installation_id=body.installation_id,
        token=body.token,
        platform=body.platform,
    )
    return NotificationTokenResponse(
        installation_id=token.installation_id,
        token=token.token,
        platform=token.platform,
        registered_at=token.registered_at,
        last_seen_at=token.last_seen_at,
    )


@users_router.delete(
    "/notification-tokens/{installation_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    response_class=Response,
)
async def delete_notification_token(
    installation_id: str,
    current_user: User = Depends(get_current_user),
) -> Response:
    """Soft-delete the row. Returns 204 regardless of whether the
    row existed — the client cares that the row is gone, not how it
    got that way (idempotent sign-out)."""
    await notification_service.delete_token(
        tenant_id=current_user.tenant_id,
        user_id=current_user.id,
        installation_id=installation_id,
    )
    return Response(status_code=status.HTTP_204_NO_CONTENT)


# ── Admin: scheduler tick ──────────────────────────────────────────────────


@admin_router.post(
    "/run-scheduler",
    response_model=SchedulerTickSummary,
)
async def run_scheduler(
    current_user: User = Depends(require_role(UserRole.tenant_admin)),
) -> SchedulerTickSummary:
    """Trigger one notification-scheduler tick across the tenant.

    Tenant-admin only. Production environments run this on a cron
    (Azure Container Apps Job or a sibling Functions timer); the
    endpoint exists so operators can dry-run a tick from the admin
    console, and so the worker is exercisable from integration
    tests without spawning a container.

    Returns counts the operator can sanity-check — "20 students
    evaluated, 3 study reminders sent, 0 failures" reads as a healthy
    tick at a glance.
    """
    summary = await scheduler.run_tick_for_tenant(
        tenant_id=current_user.tenant_id,
    )
    return SchedulerTickSummary(
        study_reminders_sent=summary.study_reminders_sent,
        streak_warnings_sent=summary.streak_warnings_sent,
        unanswered_reprompts_sent=summary.unanswered_reprompts_sent,
        students_evaluated=summary.students_evaluated,
        failures=summary.failures,
    )
