"""Notification endpoints — Sprint 5.7.

Two routes for managing per-device push registrations:

* ``POST /users/me/notification-tokens`` — upsert this device's FCM
  token. Called by the Flutter app on every cold start (FCM tokens
  rotate silently, so heartbeating is the right correctness model).
* ``DELETE /users/me/notification-tokens/{installation_id}`` —
  remove this device. Called on explicit sign-out.

A third route fires a scheduler tick — see the worker / cron section
of the project plan. Kept here so the same auth + tenant-scope
plumbing applies:

* ``POST /admin/notifications/run-scheduler`` — runs one scheduler
  tick across the caller's tenant. Tenant-admin only. Returns a
  summary so an operator can sanity-check what would fire.

Why ``/users/me`` and not ``/users/{id}``
-----------------------------------------
A device only ever knows the JWT-authenticated user — letting clients
pass an arbitrary user_id would invite a spoofing attack where one
student registers a token under another's account. Anchoring to the
caller's ``current_user.id`` removes the surface entirely.
"""

from __future__ import annotations

import logging

from fastapi import APIRouter, Depends, Response, status
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

from app.core.auth import get_current_user, require_role
from app.models.notification import DevicePlatform
from app.models.user import User, UserRole
from app.services import notifications as notification_service
from app.workers import notification_scheduler as scheduler

logger = logging.getLogger(__name__)

users_router = APIRouter(prefix="/users/me", tags=["notifications"])
admin_router = APIRouter(prefix="/admin/notifications", tags=["notifications"])


# ── Wire types ─────────────────────────────────────────────────────────────


class NotificationTokenRegistration(BaseModel):
    """Request body for ``POST /users/me/notification-tokens``."""

    installation_id: str = Field(
        min_length=1,
        max_length=128,
        description=(
            "Stable per-install UUID generated by the Flutter app. "
            "Re-installs MUST mint a fresh value so the backend "
            "replaces the old row instead of stacking duplicates."
        ),
    )
    token: str = Field(
        min_length=1,
        max_length=4096,
        description="The current FCM token for this installation.",
    )
    platform: DevicePlatform


class NotificationTokenResponse(BaseModel):
    """Echoed registration confirming what the backend stored.

    The Flutter side uses ``last_seen_at`` to know whether its
    heartbeat refresh actually landed (some Flutter networks swallow
    success codes silently and a stale ``last_seen_at`` is the
    trigger to retry on next launch).
    """

    installation_id: str
    token: str
    platform: DevicePlatform
    registered_at: str
    last_seen_at: str


class SchedulerTickSummary(BaseModel):
    """Response body for the admin scheduler-tick endpoint."""

    study_reminders_sent: int
    streak_warnings_sent: int
    unanswered_reprompts_sent: int = 0
    students_evaluated: int
    failures: int


# ── Token endpoints ────────────────────────────────────────────────────────


@users_router.post(
    "/notification-tokens",
    response_model=NotificationTokenResponse,
    status_code=status.HTTP_201_CREATED,
)
async def register_notification_token(
    body: NotificationTokenRegistration,
    current_user: User = Depends(get_current_user),
) -> NotificationTokenResponse:
    """Upsert this device's push registration.

    Always returns 201 — the registration is upserted, so "already
    registered" isn't a separate response. ``last_seen_at`` always
    bumps to wall-clock now so heartbeats are observable.
    """
    try:
        token = await notification_service.register_token(
            tenant_id=current_user.tenant_id,
            user_id=current_user.id,
            installation_id=body.installation_id,
            token=body.token,
            platform=body.platform,
        )
    except Exception as exc:
        logger.exception(
            "register_notification_token failed for user=%s installation=%s: %s",
            current_user.id,
            body.installation_id,
            exc,
        )
        return JSONResponse(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            content={
                "detail": "Push registration temporarily unavailable. Will retry on next launch."
            },
        )
    return NotificationTokenResponse(
        installation_id=token.installation_id,
        token=token.token,
        platform=token.platform,
        registered_at=token.registered_at,
        last_seen_at=token.last_seen_at,
    )


@users_router.delete(
    "/notification-tokens/{installation_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    response_class=Response,
)
async def delete_notification_token(
    installation_id: str,
    current_user: User = Depends(get_current_user),
) -> Response:
    """Soft-delete the row. Returns 204 regardless of whether the
    row existed — the client cares that the row is gone, not how it
    got that way (idempotent sign-out)."""
    await notification_service.delete_token(
        tenant_id=current_user.tenant_id,
        user_id=current_user.id,
        installation_id=installation_id,
    )
    return Response(status_code=status.HTTP_204_NO_CONTENT)


# ── Admin: scheduler tick ──────────────────────────────────────────────────


@admin_router.post(
    "/run-scheduler",
    response_model=SchedulerTickSummary,
)
async def run_scheduler(
    current_user: User = Depends(require_role(UserRole.tenant_admin)),
) -> SchedulerTickSummary:
    """Trigger one notification-scheduler tick across the tenant.

    Tenant-admin only. Production environments run this on a cron
    (Azure Container Apps Job or a sibling Functions timer); the
    endpoint exists so operators can dry-run a tick from the admin
    console, and so the worker is exercisable from integration
    tests without spawning a container.

    Returns counts the operator can sanity-check — "20 students
    evaluated, 3 study reminders sent, 0 failures" reads as a healthy
    tick at a glance.
    """
    summary = await scheduler.run_tick_for_tenant(
        tenant_id=current_user.tenant_id,
    )
    return SchedulerTickSummary(
        study_reminders_sent=summary.study_reminders_sent,
        streak_warnings_sent=summary.streak_warnings_sent,
        unanswered_reprompts_sent=summary.unanswered_reprompts_sent,
        students_evaluated=summary.students_evaluated,
        failures=summary.failures,
    )


# ── Test push endpoint ─────────────────────────────────────────────────────


class TestPushResponse(BaseModel):
    """Result of a test-push request."""

    devices_found: int
    results: list[str]
    sender_type: str


class ActivityPushRequest(BaseModel):
    title: str
    body: str
    workspace_id: str


@users_router.post(
    "/notification-tokens/activity-push",
    response_model=TestPushResponse,
    summary="Send a learning-activity push to the current user",
)
async def send_activity_push(
    body: ActivityPushRequest,
    current_user: User = Depends(get_current_user),
) -> TestPushResponse:
    """Confirm flashcard/session activity over the real push channel."""
    from app.services.notifications import (
        NotificationPayload,
        NotificationType,
        dispatch_to_user,
        get_sender,
    )

    sender = get_sender()
    results = await dispatch_to_user(
        tenant_id=current_user.tenant_id,
        user_id=current_user.id,
        payload=NotificationPayload(
            notification_type=NotificationType.study_reminder,
            title=body.title,
            body=body.body,
            data={
                "type": NotificationType.study_reminder.value,
                "workspace_id": body.workspace_id,
            },
        ),
    )
    logger.info(
        "Activity push user=%s devices=%d outcomes=%s",
        current_user.id,
        len(results),
        [result.outcome.value for result in results],
    )
    return TestPushResponse(
        devices_found=len(results),
        results=[
            f"device {index + 1}: {result.outcome.value}"
            + (f" ({result.failure_reason})" if result.failure_reason else "")
            for index, result in enumerate(results)
        ]
        or ["No registered devices found"],
        sender_type=type(sender).__name__,
    )


@users_router.post(
    "/notification-tokens/test-push",
    response_model=TestPushResponse,
    summary="Send a test push to all of your registered devices",
)
async def send_test_push(
    current_user: User = Depends(get_current_user),
) -> TestPushResponse:
    """Fire a test notification to every registered device for the calling user.

    Use this to verify end-to-end push delivery without waiting for the
    scheduler. The response tells you how many devices were found, what
    the outcome was for each, and which sender was used.

    If ``sender_type`` is ``LoggingSender`` the push was only logged
    server-side — you need to configure
    ``NOTIFICATION_HUB_CONNECTION_STRING`` + ``NOTIFICATION_HUB_NAME``
    in ``.env`` to get real pushes.
    """
    from app.services.notifications import (
        NotificationPayload,
        NotificationType,
        dispatch_to_user,
        get_sender,
    )

    sender = get_sender()
    sender_type = type(sender).__name__

    results = await dispatch_to_user(
        tenant_id=current_user.tenant_id,
        user_id=current_user.id,
        payload=NotificationPayload(
            notification_type=NotificationType.study_reminder,
            title="\U0001f514 Test notification",
            body=f"Push is working! Sent to {current_user.display_name}.",
            data={
                "type": NotificationType.study_reminder.value,
                "workspace_id": "test",
            },
        ),
    )

    result_labels = [
        f"device {i + 1}: {r.outcome.value}"
        + (f" ({r.failure_reason})" if r.failure_reason else "")
        for i, r in enumerate(results)
    ]

    return TestPushResponse(
        devices_found=len(results),
        results=result_labels if result_labels else ["No registered devices found"],
        sender_type=sender_type,
    )


# ── Admin: activity feed (Bug 3 fix) ────────────────────────────────────────


class AdminActivityItem(BaseModel):
    """A single item in the admin activity notification feed."""

    id: str
    type: str  # "document_ready" | "session_completed" | "child_progress" | "streak_milestone" | "mastery_milestone" | "badge_unlocked" | "generation_error" | "document_flagged"
    title: str
    body: str
    workspace_id: str | None = None
    workspace_name: str | None = None
    timestamp: str
    read: bool = False
    subject: str | None = None
    metric: str | None = None


class AdminActivityFeedResponse(BaseModel):
    items: list[AdminActivityItem]
    unread_count: int


@admin_router.get(
    "/activity-feed",
    response_model=AdminActivityFeedResponse,
    summary="Workspace activity feed for the admin notification inbox",
)
async def get_admin_activity_feed(
    current_user: User = Depends(require_role(UserRole.tenant_admin, UserRole.workspace_admin)),
) -> AdminActivityFeedResponse:
    """Aggregate recent workspace events into a notification-style feed.

    Combines event streams into a unified, time-sorted activity list:
    - Newly processed documents (status = 'ready' or 'error')
    - Flagged study materials awaiting review
    - Completed adaptive sessions (student activity signal)

    Returns the 50 most recent items, newest first.
    """
    from app.core.database import (
        ADAPTIVE_SESSIONS,
        DOCUMENTS,
        GAMIFICATION,
        USERS,
        WORKSPACES,
        get_collection,
    )

    tenant_id = current_user.tenant_id
    items: list[AdminActivityItem] = []

    # Fetch workspace name map for context labels
    ws_cursor = get_collection(tenant_id, WORKSPACES).find(
        {"deleted_at": None}, {"_id": 1, "name": 1}
    )
    ws_rows = await ws_cursor.to_list(length=200)
    ws_name_map: dict[str, str] = {str(row["_id"]): str(row.get("name", "")) for row in ws_rows}

    # ── Stream 1: document processing events ─────────────────────────────────
    doc_cursor = get_collection(tenant_id, DOCUMENTS).find(
        {"deleted_at": None, "status": {"$in": ["ready", "error"]}},
        {"_id": 1, "filename": 1, "status": 1, "workspace_id": 1, "updated_at": 1},
    )
    doc_rows = await doc_cursor.to_list(length=100)
    for row in doc_rows:
        doc_id = str(row.get("_id", ""))
        ws_id = str(row.get("workspace_id", ""))
        doc_status = str(row.get("status", ""))
        filename = str(row.get("filename", "Unknown file"))
        timestamp = str(row.get("updated_at", ""))
        if doc_status == "ready":
            items.append(
                AdminActivityItem(
                    id=f"doc_ready_{doc_id}",
                    type="document_ready",
                    title="\U0001f4c4 Document Ready",
                    body=f"'{filename}' finished processing. Questions are being generated.",
                    workspace_id=ws_id,
                    workspace_name=ws_name_map.get(ws_id),
                    timestamp=timestamp,
                )
            )
        elif doc_status == "error":
            items.append(
                AdminActivityItem(
                    id=f"doc_error_{doc_id}",
                    type="generation_error",
                    title="\u26a0\ufe0f Processing Failed",
                    body=f"'{filename}' could not be processed. Please re-upload or check the file.",
                    workspace_id=ws_id,
                    workspace_name=ws_name_map.get(ws_id),
                    timestamp=timestamp,
                )
            )

    # ── Stream 2: flagged uploads awaiting parent review ─────────────────────
    flagged_cursor = get_collection(tenant_id, DOCUMENTS).find(
        {"deleted_at": None, "moderation_flagged": True},
        {"_id": 1, "filename": 1, "workspace_id": 1, "updated_at": 1},
    )
    flagged_rows = await flagged_cursor.to_list(length=50)
    for row in flagged_rows:
        doc_id = str(row.get("_id", ""))
        ws_id = str(row.get("workspace_id", ""))
        filename = str(row.get("filename", "Unknown file"))
        timestamp = str(row.get("updated_at", ""))
        items.append(
            AdminActivityItem(
                id=f"flagged_{doc_id}",
                type="document_flagged",
                title="\u26a0\ufe0f Flagged Upload Alert",
                body=f"'{filename}' was flagged for safety review. Parent approval required.",
                workspace_id=ws_id,
                workspace_name=ws_name_map.get(ws_id),
                timestamp=timestamp,
            )
        )

    # ── Stream 3: recent student sessions (activity & progress signal) ───────
    session_cursor = get_collection(tenant_id, ADAPTIVE_SESSIONS).find(
        {"status": {"$in": ["completed", "timed_out", "exited"]}},
        {
            "_id": 1,
            "student_id": 1,
            "workspace_id": 1,
            "mode": 1,
            "plan": 1,
            "summary": 1,
            "accuracy_percentage": 1,
            "xp_gained": 1,
            "completed_count": 1,
            "correct_count": 1,
            "completed_at": 1,
        },
    )
    session_rows = await session_cursor.to_list(length=100)
    student_ids = list(
        {str(row.get("student_id", "")) for row in session_rows if row.get("student_id")}
    )
    student_names: dict[str, str] = {}
    if student_ids:
        user_cursor = get_collection(tenant_id, USERS).find(
            {"_id": {"$in": student_ids}}, {"_id": 1, "display_name": 1}
        )
        for u in await user_cursor.to_list(length=200):
            student_names[str(u["_id"])] = str(u.get("display_name", "A student"))

    for row in session_rows:
        sid = str(row.get("_id", ""))
        ws_id = str(row.get("workspace_id", ""))
        mode = str(row.get("mode", "study")).capitalize()
        student = student_names.get(str(row.get("student_id", "")), "A student")
        ts = str(row.get("completed_at", ""))

        plan_data = row.get("plan") or {}
        summary_data = row.get("summary") or {}
        subject = plan_data.get("subject") or row.get("subject")
        subcat = plan_data.get("subcategory") or row.get("subcategory")

        accuracy = row.get("accuracy_percentage")
        if accuracy is None and "accuracy_percentage" in summary_data:
            accuracy = summary_data.get("accuracy_percentage")
        xp = row.get("xp_gained")
        if xp is None and "xp_gained" in summary_data:
            xp = summary_data.get("xp_gained")

        acc_str = f"{int(accuracy)}%" if accuracy is not None else ""
        xp_str = f"+{xp} XP" if xp else ""
        metric_parts = [p for p in [acc_str, xp_str] if p]
        metric = " • ".join(metric_parts) if metric_parts else None

        if subject:
            title = f"\U0001f3af {student}: {subject} Progress"
            subcat_note = f" on '{subcat}'" if subcat else ""
            acc_note = f" with {acc_str} accuracy" if acc_str else ""
            xp_note = f" (earned {xp_str})" if xp_str else ""
            body = f"{student} finished a {subject} study session{subcat_note}{acc_note}{xp_note}."
            notif_type = "child_progress"
        else:
            title = f"\U0001f393 {student}: {mode} Session"
            acc_note = f" \u2014 {acc_str} accuracy" if acc_str else ""
            xp_note = f" ({xp_str})" if xp_str else ""
            body = f"{student} completed a {mode.lower()} session{acc_note}{xp_note}."
            notif_type = "session_completed"

        items.append(
            AdminActivityItem(
                id=f"session_{sid}",
                type=notif_type,
                title=title,
                body=body,
                workspace_id=ws_id,
                workspace_name=ws_name_map.get(ws_id),
                timestamp=ts,
                subject=subject,
                metric=metric,
            )
        )

    # ── Stream 4: gamification streaks & milestones ──────────────────────────
    gamif_cursor = get_collection(tenant_id, GAMIFICATION).find(
        {"deleted_at": None},
        {
            "_id": 1,
            "student_id": 1,
            "workspace_id": 1,
            "streak_days": 1,
            "level": 1,
            "xp_total": 1,
            "badges": 1,
            "updated_at": 1,
        },
    )
    gamif_rows = await gamif_cursor.to_list(length=50)
    for g in gamif_rows:
        sid = str(g.get("student_id", ""))
        ws_id = str(g.get("workspace_id", ""))
        student = student_names.get(sid, "A student")
        streak = g.get("streak_days", 0)
        level = g.get("level", 1)
        xp_total = g.get("xp_total", 0)
        ts = str(g.get("updated_at") or "")

        if streak >= 3:
            items.append(
                AdminActivityItem(
                    id=f"streak_{sid}_{streak}",
                    type="streak_milestone",
                    title=f"\U0001f525 {student} Streak Milestone!",
                    body=f"{student} is on a {streak}-day active study streak! Consistency is accelerating mastery.",
                    workspace_id=ws_id,
                    workspace_name=ws_name_map.get(ws_id),
                    timestamp=ts,
                    metric=f"{streak}-Day Streak",
                )
            )

        if level > 1:
            items.append(
                AdminActivityItem(
                    id=f"level_{sid}_{level}",
                    type="mastery_milestone",
                    title=f"\U0001f3c6 {student} Reached Level {level}!",
                    body=f"{student} advanced to Level {level} with {xp_total} total XP earned.",
                    workspace_id=ws_id,
                    workspace_name=ws_name_map.get(ws_id),
                    timestamp=ts,
                    metric=f"Level {level}",
                )
            )

        badges = g.get("badges") or []
        for b in badges[-2:]:
            badge_name = b.get("name", "Achievement")
            badge_desc = b.get("description", "")
            badge_ts = b.get("earned_at") or ts
            badge_id = b.get("badge_id", "")
            items.append(
                AdminActivityItem(
                    id=f"badge_{sid}_{badge_id}",
                    type="badge_unlocked",
                    title=f"\U0001f396\ufe0f {student} Earned '{badge_name}'",
                    body=f"{badge_desc} (+{b.get('xp_reward', 0)} XP reward)",
                    workspace_id=ws_id,
                    workspace_name=ws_name_map.get(ws_id),
                    timestamp=badge_ts,
                    metric=badge_name,
                )
            )

    # Sort newest first and cap at 75
    items.sort(key=lambda x: x.timestamp, reverse=True)
    items = items[:75]
    return AdminActivityFeedResponse(items=items, unread_count=len(items))
