"""Notification endpoints — Sprint 5.7.

Two routes for managing per-device push registrations:

* ``POST /users/me/notification-tokens`` — upsert this device's FCM
  token. Called by the Flutter app on every cold start (FCM tokens
  rotate silently, so heartbeating is the right correctness model).
* ``DELETE /users/me/notification-tokens/{installation_id}`` —
  remove this device. Called on explicit sign-out.

A third route fires a scheduler tick — see the worker / cron section
of the project plan. Kept here so the same auth + tenant-scope
plumbing applies:

* ``POST /admin/notifications/run-scheduler`` — runs one scheduler
  tick across the caller's tenant. Tenant-admin only. Returns a
  summary so an operator can sanity-check what would fire.

Why ``/users/me`` and not ``/users/{id}``
-----------------------------------------
A device only ever knows the JWT-authenticated user — letting clients
pass an arbitrary user_id would invite a spoofing attack where one
student registers a token under another's account. Anchoring to the
caller's ``current_user.id`` removes the surface entirely.
"""

from __future__ import annotations

import logging

from fastapi import APIRouter, Depends, Response, status
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

from app.core.auth import get_current_user, require_role
from app.models.notification import DevicePlatform
from app.models.user import User, UserRole
from app.services import notifications as notification_service
from app.workers import notification_scheduler as scheduler

logger = logging.getLogger(__name__)

users_router = APIRouter(prefix="/users/me", tags=["notifications"])
admin_router = APIRouter(prefix="/admin/notifications", tags=["notifications"])


# ── Wire types ─────────────────────────────────────────────────────────────


class NotificationTokenRegistration(BaseModel):
    """Request body for ``POST /users/me/notification-tokens``."""

    installation_id: str = Field(
        min_length=1,
        max_length=128,
        description=(
            "Stable per-install UUID generated by the Flutter app. "
            "Re-installs MUST mint a fresh value so the backend "
            "replaces the old row instead of stacking duplicates."
        ),
    )
    token: str = Field(
        min_length=1,
        max_length=4096,
        description="The current FCM token for this installation.",
    )
    platform: DevicePlatform


class NotificationTokenResponse(BaseModel):
    """Echoed registration confirming what the backend stored.

    The Flutter side uses ``last_seen_at`` to know whether its
    heartbeat refresh actually landed (some Flutter networks swallow
    success codes silently and a stale ``last_seen_at`` is the
    trigger to retry on next launch).
    """

    installation_id: str
    token: str
    platform: DevicePlatform
    registered_at: str
    last_seen_at: str


class SchedulerTickSummary(BaseModel):
    """Response body for the admin scheduler-tick endpoint."""

    study_reminders_sent: int
    streak_warnings_sent: int
    unanswered_reprompts_sent: int = 0
    students_evaluated: int
    failures: int


# ── Token endpoints ────────────────────────────────────────────────────────


@users_router.post(
    "/notification-tokens",
    response_model=NotificationTokenResponse,
    status_code=status.HTTP_201_CREATED,
)
async def register_notification_token(
    body: NotificationTokenRegistration,
    current_user: User = Depends(get_current_user),
) -> NotificationTokenResponse:
    """Upsert this device's push registration.

    Always returns 201 — the registration is upserted, so "already
    registered" isn't a separate response. ``last_seen_at`` always
    bumps to wall-clock now so heartbeats are observable.
    """
    try:
        token = await notification_service.register_token(
            tenant_id=current_user.tenant_id,
            user_id=current_user.id,
            installation_id=body.installation_id,
            token=body.token,
            platform=body.platform,
        )
    except Exception as exc:
        logger.exception(
            "register_notification_token failed for user=%s installation=%s: %s",
            current_user.id,
            body.installation_id,
            exc,
        )
        return JSONResponse(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            content={"detail": "Push registration temporarily unavailable. Will retry on next launch."},
        )
    return NotificationTokenResponse(
        installation_id=token.installation_id,
        token=token.token,
        platform=token.platform,
        registered_at=token.registered_at,
        last_seen_at=token.last_seen_at,
    )


@users_router.delete(
    "/notification-tokens/{installation_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    response_class=Response,
)
async def delete_notification_token(
    installation_id: str,
    current_user: User = Depends(get_current_user),
) -> Response:
    """Soft-delete the row. Returns 204 regardless of whether the
    row existed — the client cares that the row is gone, not how it
    got that way (idempotent sign-out)."""
    await notification_service.delete_token(
        tenant_id=current_user.tenant_id,
        user_id=current_user.id,
        installation_id=installation_id,
    )
    return Response(status_code=status.HTTP_204_NO_CONTENT)


# ── Admin: scheduler tick ──────────────────────────────────────────────────


@admin_router.post(
    "/run-scheduler",
    response_model=SchedulerTickSummary,
)
async def run_scheduler(
    current_user: User = Depends(require_role(UserRole.tenant_admin)),
) -> SchedulerTickSummary:
    """Trigger one notification-scheduler tick across the tenant.

    Tenant-admin only. Production environments run this on a cron
    (Azure Container Apps Job or a sibling Functions timer); the
    endpoint exists so operators can dry-run a tick from the admin
    console, and so the worker is exercisable from integration
    tests without spawning a container.

    Returns counts the operator can sanity-check — "20 students
    evaluated, 3 study reminders sent, 0 failures" reads as a healthy
    tick at a glance.
    """
    summary = await scheduler.run_tick_for_tenant(
        tenant_id=current_user.tenant_id,
    )
    return SchedulerTickSummary(
        study_reminders_sent=summary.study_reminders_sent,
        streak_warnings_sent=summary.streak_warnings_sent,
        unanswered_reprompts_sent=summary.unanswered_reprompts_sent,
        students_evaluated=summary.students_evaluated,
        failures=summary.failures,
    )


# ── Test push endpoint ─────────────────────────────────────────────────────


class TestPushResponse(BaseModel):
    """Result of a test-push request."""

    devices_found: int
    results: list[str]
    sender_type: str


class ActivityPushRequest(BaseModel):
    title: str
    body: str
    workspace_id: str


@users_router.post(
    "/notification-tokens/activity-push",
    response_model=TestPushResponse,
    summary="Send a learning-activity push to the current user",
)
async def send_activity_push(
    body: ActivityPushRequest,
    current_user: User = Depends(get_current_user),
) -> TestPushResponse:
    """Confirm flashcard/session activity over the real push channel."""
    from app.services.notifications import (
        NotificationPayload,
        NotificationType,
        dispatch_to_user,
        get_sender,
    )

    sender = get_sender()
    results = await dispatch_to_user(
        tenant_id=current_user.tenant_id,
        user_id=current_user.id,
        payload=NotificationPayload(
            notification_type=NotificationType.study_reminder,
            title=body.title,
            body=body.body,
            data={
                "type": NotificationType.study_reminder.value,
                "workspace_id": body.workspace_id,
            },
        ),
    )
    return TestPushResponse(
        devices_found=len(results),
        results=[
            f"device {index + 1}: {result.outcome.value}"
            + (f" ({result.failure_reason})" if result.failure_reason else "")
            for index, result in enumerate(results)
        ] or ["No registered devices found"],
        sender_type=type(sender).__name__,
    )


@users_router.post(
    "/notification-tokens/test-push",
    response_model=TestPushResponse,
    summary="Send a test push to all of your registered devices",
)
async def send_test_push(
    current_user: User = Depends(get_current_user),
) -> TestPushResponse:
    """Fire a test notification to every registered device for the calling user.

    Use this to verify end-to-end push delivery without waiting for the
    scheduler. The response tells you how many devices were found, what
    the outcome was for each, and which sender was used.

    If ``sender_type`` is ``LoggingSender`` the push was only logged
    server-side — you need to configure
    ``NOTIFICATION_HUB_CONNECTION_STRING`` + ``NOTIFICATION_HUB_NAME``
    in ``.env`` to get real pushes.
    """
    from app.services.notifications import (
        NotificationPayload,
        NotificationType,
        dispatch_to_user,
        get_sender,
    )

    sender = get_sender()
    sender_type = type(sender).__name__

    results = await dispatch_to_user(
        tenant_id=current_user.tenant_id,
        user_id=current_user.id,
        payload=NotificationPayload(
            notification_type=NotificationType.study_reminder,
            title="🔔 Test notification",
            body=f"Push is working! Sent to {current_user.display_name}.",
            data={
                "type": NotificationType.study_reminder.value,
                "workspace_id": "test",
            },
        ),
    )

    result_labels = [
        f"device {i + 1}: {r.outcome.value}"
        + (f" ({r.failure_reason})" if r.failure_reason else "")
        for i, r in enumerate(results)
    ]

    return TestPushResponse(
        devices_found=len(results),
        results=result_labels if result_labels else ["No registered devices found"],
        sender_type=sender_type,
    )

